### ISSUE TITLE
Does not compile on Ubuntu 14.04 64bit

### ISSUE THREAD

**Issue by fricklerhandwerk** [rlane/Oort-legacy#40]
Hi! I wanted to get the game running, but after installing all dependencies, running `./autogen.sh` and `./configure` I get

```
/usr/bin/ld: ../third_party/luajit/src/libluajit.a(lib_package.o): undefined reference to symbol 'dlclose@@GLIBC_2.2.5'
//lib/x86_64-linux-gnu/libdl.so.2: error adding symbols: DSO missing from command line
```

I got past the error by adding `-ldl` to `dedicated/Makefile` line 135.

But then `ui/oort.vala` complains loudly:

```
gtk+-2.0.vapi:5926.40-5926.42: warning: Gtk is deprecated. Use gtk+-3.0
oort.vala:18.19-18.26: error: `MenuItem' is an ambiguous reference between `GLib.MenuItem' and `Gtk.MenuItem'
            var item = new MenuItem.with_mnemonic(label);
                           ^^^^^^^^
oort.vala:18.8-18.47: error: var declaration not allowed with non-typed initializer
            var item = new MenuItem.with_mnemonic(label);
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
oort.vala:19.18-19.21: error: The name `item' does not exist in the context of `Oort.MenuBuilder.leaf'
            parent.append(item);
                          ^^^^
oort.vala:20.4-20.7: error: The name `item' does not exist in the context of `Oort.MenuBuilder.leaf'
            item.activate.connect((widget) => action());
            ^^^^
oort.vala:25.19-25.26: error: `MenuItem' is an ambiguous reference between `GLib.MenuItem' and `Gtk.MenuItem'
            var item = new MenuItem.with_mnemonic(label);
                           ^^^^^^^^
oort.vala:25.8-25.47: error: var declaration not allowed with non-typed initializer
            var item = new MenuItem.with_mnemonic(label);
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
oort.vala:26.19-26.22: error: `Menu' is an ambiguous reference between `GLib.Menu' and `Gtk.Menu'
            var menu = new Menu();
                           ^^^^
oort.vala:27.4-27.7: error: The name `item' does not exist in the context of `Oort.MenuBuilder.menu'
            item.set_submenu(menu);
            ^^^^
oort.vala:28.18-28.21: error: The name `item' does not exist in the context of `Oort.MenuBuilder.menu'
            parent.append(item);
                          ^^^^
oort.vala:29.12-29.15: error: Argument 1: Cannot convert from `GLib.Menu' to `Gtk.MenuShell'
            builder(menu);
                    ^^^^
oort.vala:207.4-207.10: error: `Timeout' is an ambiguous reference between `GLib.Timeout' and `Gtk.Timeout'
            Timeout.add(0, after_tick);
            ^^^^^^^
log.vala:36.16-36.19: error: Argument 1: Cannot pass value to reference or output parameter
                buf.insert(iter, "(dead)", -1);
                           ^^^^
log.vala:45.17-45.20: error: Argument 1: Cannot pass value to reference or output parameter
                    buf.insert(iter, e, -1);
                               ^^^^
log.vala:47.17-47.20: error: Argument 1: Cannot pass value to reference or output parameter
                    buf.insert(iter, "\n", 1);
                               ^^^^
Compilation failed: 14 error(s), 34 warning(s)
```

Maybe you can help?
